<?php 
 /*------------------------------------------------------------------------
  * Bumble Extension Module 
  * @package             SocialConnect
  * @author              Lanzillo Ferdinando, Sabatino Francesco
  * @copyright           Copyright (C) 2016 http://www.armah.it/armah-extension-en/ All Rights Reserved.
  * @license             http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
  * @Technical-Support   http://www.armah.it/armah-extension-en/
------------------------------------------------------------------------*/
?>
<div class="bumble-filterlist-page">
	<h1><?php echo $this->__( $this->getTitleFilter() );?></h1>

	<div class="filter-wrapper bumbleclear layout-grid">
		<ul>
		<?php $filters = $this->getFilters(); ?>
		<?php foreach( $filters as $filter ): ?>
			<li class="filter-item">
				<a class="filter-logo" href="<?php echo $filter->getLink();?>" title="<?php echo $filter->getTitle();?>">
					<img src="<?php echo $filter->getIconUrl();?>" alt="<?php echo $filter->getTitle();?>" />
				</a>
				<a class="filter-title" href="<?php echo $filter->getLink();?>" title="<?php echo $filter->getTitle();?>">
					<span><?php echo $filter->getTitle();?></span>
				</a>
			</li>
		<?php endforeach; ?>
		</ul>
	</div>
	<?php echo $this->getChildHtml('filter.list.toolbar'); ?>
</div>