<?php
/*------------------------------------------------------------------------
  * Bumble Extension Module 
  * @package             SocialConnect
  * @author              Lanzillo Ferdinando, Sabatino Francesco
  * @copyright           Copyright (C) 2016 http://www.armah.it/armah-extension-en/ All Rights Reserved.
  * @license             http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
  * @Technical-Support   http://www.armah.it/armah-extension-en/
---------------------------------------------------------------------------*/
?>
<?php
	$enable_show = Mage::getStoreConfig( 'bumble_filter/module_setting/enable_filternavmodule' );
	$title_filternav = Mage::getStoreConfig( 'bumble_filter/module_setting/filternav_title' );
	//$filter_filternav = Mage::getStoreConfig( 'bumble_filter/module_setting/filter_group' );
	//var_dump($filter_filternav);

	$collection = $this->getCategoryFilters();
	//var_dump($collection);
?>
<?php $coll = Mage::getModel('bumble_filter/filter')->getCollection(); ?>
    <?php $count = array(); ?>
    <?php foreach( $collection as $menu ): ?>	
			<?php foreach( $coll as $countColl ): ?>
				<?php if($menu->getFilterId() == $countColl->getFilterId()) : ?>	
					<?php $count[] = $countColl->getTitle(); ?>
				<?php endif; ?>	
			<?php endforeach; ?>
	<?php endforeach; ?>
<?php if($enable_show == 1) : ?>
<?php $countArray= count($count); if($countArray != 0) : ?>
<div class="bumble-filter-menu block">
	 <div class="block-title">
        <strong>
            <span><?php echo $this->__($title_filternav) ?></span>
        </strong>
    </div>

	<div class="block-content">
	<?php //if( count($collection) ): ?>
		<ul id="filter-menu">
		<?php
			$obj = new Bumble_Filter_Block_Filter_List;

			$title = $obj->_getTitleCurrentGroup(); 
		 ?>
		<?php foreach( $collection as $menu ): ?>	
			<?php if($title != $menu->getTitle()) : ?>
			<li class="parent">
				<a href="<?php echo Mage::getBaseUrl().$menu->getIdentifier(); ?>" title="<?php echo $menu->getTitle(); ?>">
					<span><?php echo $menu->getTitle(); ?></span>
				</a>
			</li>
			<?php endif; ?>
		<?php endforeach; ?>
		
		</ul>
		
	<?php// endif; ?>
	</div>
</div>
<?php endif;//if count gt 1 ?>
<?php endif; ?>